version: '3'

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./sistemaVendasApp:/sistemaVendasApp
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    environment: 
      - DB_HOST=db
      - DB_NAME=sistemaVendasApp
      - DB_USER=postgres
      - DB_PASS=123456
    depends_on:
      - db
      
  db:
    image: postgres:10-alpine
    environment: 
      - POSTGRES_DB=sistemaVendasApp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456