# Generated by Django 3.2 on 2021-04-27 01:18

from django.db import migrations, models
import sales.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(validators=[sales.models.validators.greater_than_zero], verbose_name='Product quantity'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0.0, validators=[sales.models.validators.greater_than_zero], verbose_name='Price from product or service'),
        ),
    ]
